version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/burn-algorithms"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      rs-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      gh-dependency:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directories:
      - "/covid19"
      - "/fraud-detection"
      - "/rul-turbofan"
    schedule:
      interval: "monthly"
      day: "monday"
    groups:
      pip-dependency:
        patterns:
          - "*"
